# Generated by Django 5.2.11 on 2026-02-22 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(blank=True, default="email", max_length=30),
        ),
        migrations.CreateModel(
            name="VCSAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("github", "GitHub"), ("gitlab", "GitLab")],
                        max_length=20,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=255)),
                ("encrypted_access_token", models.TextField()),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vcs_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["provider"],
                "unique_together": {("user", "provider")},
            },
        ),
    ]
