# Generated by Django 5.2.11 on 2026-04-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_auth_provider_vcsaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="platform_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUPPORT", "Support"),
                    ("FINANCE", "Finance"),
                    ("OPERATIONS", "Operations"),
                ],
                default="",
                help_text="Internal platform team role for limited staff access.",
                max_length=20,
            ),
        ),
    ]
