# Generated by Django 5.2.11 on 2026-02-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationinvite",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
