# Generated by Django 5.2.11 on 2026-02-25 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud", "0002_cloudaccount_aws_default_region_and_more"),
        ("deployments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="cloud_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="cloud.cloudaccount",
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instance",
            name="provisioning_log",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="instance",
            name="region",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="instance",
            name="size",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="instance",
            name="terraform_state_path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.CreateModel(
            name="TerraformRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                ("command", models.TextField(blank=True)),
                ("output_log", models.TextField(blank=True)),
                ("error_log", models.TextField(blank=True)),
                (
                    "state_file_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terraform_run",
                        to="deployments.instance",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
