# Generated by Django 5.2.11 on 2026-02-25 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud", "0002_cloudaccount_aws_default_region_and_more"),
        ("deployments", "0002_instance_cloud_account_instance_ip_address_and_more"),
        ("organizations", "0003_add_first_name_to_invite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OdooServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "odoo_version",
                    models.CharField(
                        choices=[("18", "Odoo 18"), ("19", "Odoo 19")], max_length=2
                    ),
                ),
                ("region", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=50)),
                (
                    "provider_server_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "dns_domain",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("firewall_configured", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROVISIONING", "Provisioning"),
                            ("CONFIGURING", "Configuring"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                            ("DELETED", "Deleted"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "terraform_state_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("provisioning_log", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cloud_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="odoo_servers",
                        to="cloud.cloudaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_odoo_servers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odoo_servers",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OdooInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("db_name", models.CharField(max_length=255)),
                ("domain", models.CharField(blank=True, default="", max_length=255)),
                ("http_port", models.PositiveIntegerField(default=8069)),
                (
                    "systemd_service",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "nginx_site",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("ssl_enabled", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIGURING", "Configuring"),
                            ("RUNNING", "Running"),
                            ("FAILED", "Failed"),
                            ("DELETED", "Deleted"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("provisioning_log", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_odoo_instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odoo_instances",
                        to="organizations.organization",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="deployments.odooserver",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="odooserver",
            index=models.Index(
                fields=["organization", "odoo_version"],
                name="deployments_organiz_0a02bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="odooserver",
            index=models.Index(
                fields=["organization", "status"], name="deployments_organiz_c5d391_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="odooinstance",
            index=models.Index(
                fields=["organization", "status"], name="deployments_organiz_818cba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="odooinstance",
            index=models.Index(
                fields=["server", "status"], name="deployments_server__044dda_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="odooinstance",
            unique_together={("server", "db_name")},
        ),
    ]
