# Generated by Django 5.2.11 on 2026-02-25 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud", "0002_cloudaccount_aws_default_region_and_more"),
        ("deployments", "0003_odooserver_odooinstance_and_more"),
        ("organizations", "0003_add_first_name_to_invite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="odooinstance",
            unique_together={("server", "db_name"), ("server", "http_port")},
        ),
        migrations.AddField(
            model_name="odooinstance",
            name="requested_cpu_cores",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="odooinstance",
            name="requested_ram_mb",
            field=models.PositiveIntegerField(default=1024),
        ),
        migrations.AddField(
            model_name="odooserver",
            name="capacity_cpu_cores",
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="odooserver",
            name="capacity_ram_mb",
            field=models.PositiveIntegerField(default=8192),
        ),
        migrations.AddField(
            model_name="odooserver",
            name="max_instances",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="odooserver",
            name="max_port",
            field=models.PositiveIntegerField(default=8100),
        ),
        migrations.AddField(
            model_name="odooserver",
            name="min_port",
            field=models.PositiveIntegerField(default=8069),
        ),
        migrations.AlterField(
            model_name="odooserver",
            name="cloud_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="odoo_servers",
                to="cloud.cloudaccount",
            ),
        ),
        migrations.AlterField(
            model_name="odooserver",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROVISIONING", "Provisioning"),
                    ("CONFIGURING", "Configuring"),
                    ("PROVISIONED", "Provisioned"),
                    ("FAILED", "Failed"),
                    ("DELETED", "Deleted"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Infrastructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "infra_type",
                    models.CharField(
                        choices=[
                            ("PYOS", "PYOS (SSH / VPS)"),
                            ("MANAGED", "Managed Cloud"),
                        ],
                        max_length=15,
                    ),
                ),
                ("is_connected", models.BooleanField(default=False)),
                ("validation_log", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cloud_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deploy_infrastructure",
                        to="cloud.cloudaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_infrastructure",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "external_server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deploy_infrastructure",
                        to="cloud.externalserver",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deploy_infrastructure",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.AddField(
            model_name="odooserver",
            name="infrastructure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="servers",
                to="deployments.infrastructure",
            ),
        ),
    ]
