# Generated by Django 5.2.11 on 2026-03-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0004_alter_odooinstance_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="odooserver",
            name="is_reachable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="odooserver",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="odooserver",
            name="odoo_version",
            field=models.CharField(
                choices=[("17", "Odoo 17"), ("18", "Odoo 18"), ("19", "Odoo 19")],
                max_length=2,
            ),
        ),
    ]
