# Generated by Django 5.2.11 on 2026-03-12 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0005_connectivity_check"),
        ("organizations", "0003_add_first_name_to_invite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="odooinstance",
            name="is_reachable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="odooinstance",
            name="last_health_check",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="odooinstance",
            name="restart_policy",
            field=models.CharField(
                choices=[
                    ("always", "Always"),
                    ("on-failure", "On Failure"),
                    ("no", "No"),
                ],
                default="always",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="OdooInstanceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_name", models.CharField(max_length=255)),
                ("domain", models.CharField(blank=True, max_length=255)),
                ("http_port", models.PositiveIntegerField()),
                ("odoo_version", models.CharField(max_length=2)),
                ("server_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("systemd_service", models.CharField(blank=True, max_length=255)),
                ("ssl_enabled", models.BooleanField(default=False)),
                ("status", models.CharField(max_length=20)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("deployed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deployed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instance_deploys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="deployments.odooinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["-deployed_at"],
            },
        ),
        migrations.CreateModel(
            name="OdooServerHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_version", models.CharField(max_length=2)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("dns_domain", models.CharField(blank=True, max_length=255)),
                ("region", models.CharField(blank=True, max_length=50)),
                ("size", models.CharField(blank=True, max_length=50)),
                ("status", models.CharField(max_length=20)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("deployed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deployed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="server_deploys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="deployments.odooserver",
                    ),
                ),
            ],
            options={
                "ordering": ["-deployed_at"],
            },
        ),
        migrations.CreateModel(
            name="DeploymentJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("PROVISION_SERVER", "Provision Server"),
                            ("CONFIGURE_SERVER", "Configure Server"),
                            ("CREATE_INSTANCE", "Create Instance"),
                            ("DELETE_INSTANCE", "Delete Instance"),
                            ("ROLLBACK_INSTANCE", "Rollback Instance"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="QUEUED",
                        max_length=15,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("log", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deployment_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "odoo_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="deployments.odooinstance",
                    ),
                ),
                (
                    "odoo_server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="deployments.odooserver",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployment_jobs",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="deployments_organiz_2a66c6_idx",
                    ),
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="deployments_organiz_591b65_idx",
                    ),
                ],
            },
        ),
    ]
