# Generated by Django 5.2.11 on 2026-03-17 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0007_docker_deployment_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerSSHKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-friendly name, e.g. 'Alice MacBook'",
                        max_length=120,
                    ),
                ),
                (
                    "public_key",
                    models.TextField(
                        help_text="Full public key string (ssh-ed25519 / ssh-rsa …)"
                    ),
                ),
                (
                    "deployed",
                    models.BooleanField(
                        default=False,
                        help_text="True once the key has been written to the server's authorized_keys.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_server_ssh_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssh_keys",
                        to="deployments.odooserver",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("server", "public_key")},
            },
        ),
    ]
