# Generated by Django 5.2.11 on 2026-03-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0012_odooinstance_git_repos_phase1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odooserver',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROVISIONING', 'Provisioning'), ('CONFIGURING', 'Configuring'), ('PROVISIONED', 'Provisioned'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], default='PENDING', max_length=20),
        ),
    ]
