from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0013_alter_odooserver_status"),
    ]

    operations = [
        # This branch is intentionally a no-op.
        #
        # The actual schema changes for the git addon manager were generated into
        # sibling migration `0014_odooinstancegitrepo_default_branch_and_more`.
        # Keeping this file empty preserves the merge migration chain
        # (`0015_merge_20260327_2316`) without attempting to create duplicate
        # tables/columns on databases that already applied the autogenerated
        # migration first.
    ]
