# Generated by Django 5.2.11 on 2026-03-27 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0013_alter_odooserver_status'),
        ('organizations', '0003_add_first_name_to_invite'),
        ('users', '0002_user_auth_provider_vcsaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='odooinstancegitrepo',
            name='default_branch',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='odooinstancegitrepo',
            name='last_detected_modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='odooinstancegitrepo',
            name='last_remote_commit',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='odooinstancegitrepo',
            name='last_sync_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odooinstancegitrepo',
            name='last_sync_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='odooinstancegitrepo',
            name='last_sync_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odooinstancegitrepo',
            name='pinned_commit',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='odooinstancegitrepo',
            name='previous_commit',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='deploymentjob',
            name='job_type',
            field=models.CharField(choices=[('PROVISION_SERVER', 'Provision Server'), ('CONFIGURE_SERVER', 'Configure Server'), ('CREATE_INSTANCE', 'Create Instance'), ('DELETE_INSTANCE', 'Delete Instance'), ('ROLLBACK_INSTANCE', 'Rollback Instance'), ('CLONE_INSTANCE_REPO', 'Clone Instance Repo'), ('UPDATE_INSTANCE_REPO', 'Update Instance Repo'), ('CHECKOUT_INSTANCE_REPO_BRANCH', 'Checkout Instance Repo Branch'), ('REMOVE_INSTANCE_REPO', 'Remove Instance Repo'), ('REFRESH_INSTANCE_ADDONS', 'Refresh Instance Addons'), ('ROLLBACK_INSTANCE_REPO', 'Rollback Instance Repo'), ('AUTO_SYNC_INSTANCE_REPOS', 'Auto Sync Instance Repos')], max_length=30),
        ),
        migrations.CreateModel(
            name='GitRepositoryCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('auth_type', models.CharField(choices=[('PUBLIC', 'Public'), ('GITHUB_OAUTH', 'GitHub OAuth'), ('TOKEN', 'Personal access token'), ('SSH_KEY', 'SSH key')], default='PUBLIC', max_length=20)),
                ('git_username', models.CharField(blank=True, default='', max_length=255)),
                ('encrypted_access_token', models.TextField(blank=True, default='')),
                ('encrypted_ssh_private_key', models.TextField(blank=True, default='')),
                ('encrypted_ssh_key_passphrase', models.TextField(blank=True, default='')),
                ('ssh_public_key', models.TextField(blank=True, default='')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_git_repo_credentials', to=settings.AUTH_USER_MODEL)),
                ('github_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_git_credentials', to='users.vcsaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_repo_credentials', to='organizations.organization')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='odooinstancegitrepo',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='git_repos', to='deployments.gitrepositorycredential'),
        ),
        migrations.AddIndex(
            model_name='gitrepositorycredential',
            index=models.Index(fields=['organization', 'auth_type'], name='dep_git_cred_org_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gitrepositorycredential',
            unique_together={('organization', 'name')},
        ),
    ]
