# Generated by Django 5.2.11 on 2026-03-27 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0014_git_addon_manager_phase2_plus'),
        ('deployments', '0014_odooinstancegitrepo_default_branch_and_more'),
    ]

    operations = [
    ]
