# Generated by Django 5.2.11 on 2026-04-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0022_alter_deploymentjob_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="odooserver",
            name="enterprise_shared_path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="odooserver",
            name="enterprise_shared_release_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
