# Generated by Django 5.2.11 on 2026-04-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0023_server_enterprise_shared_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="odooserver",
            name="celery_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="odooserver",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONNECTING", "Connecting"),
                    ("PROVISIONING", "Provisioning"),
                    ("CONFIGURING", "Configuring"),
                    ("PROVISIONED", "Provisioned"),
                    ("FAILED", "Failed"),
                    ("ARCHIVED", "Archived"),
                    ("DELETED", "Deleted"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
