# Generated by Django 5.2.11 on 2026-04-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0024_connecting_status_celery_task_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repository", models.CharField(max_length=255)),
                ("branch", models.CharField(blank=True, max_length=120)),
                ("head_commit_sha", models.CharField(blank=True, max_length=64)),
                ("head_commit_message", models.CharField(blank=True, max_length=500)),
                ("pusher_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSED", "Processed"),
                            ("IGNORED", "Ignored"),
                            ("ERROR", "Error"),
                        ],
                        default="PROCESSED",
                        max_length=20,
                    ),
                ),
                ("ignore_reason", models.CharField(blank=True, max_length=255)),
                ("matched_repo_ids", models.JSONField(default=list)),
                ("queued_repo_ids", models.JSONField(default=list)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["repository", "branch"],
                        name="dep_webhook_repo_branch_idx",
                    ),
                    models.Index(
                        fields=["received_at"], name="dep_webhook_received_idx"
                    ),
                ],
            },
        ),
    ]
