# Generated by Django 5.2.11 on 2026-04-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0025_githubwebhookevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odooinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIGURING", "Configuring"),
                    ("RUNNING", "Running"),
                    ("STOPPED", "Stopped"),
                    ("FAILED", "Failed"),
                    ("DELETED", "Deleted"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
