# Generated by Django 5.2.11 on 2026-04-11 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0026_add_stopped_instance_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="deploymentjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("PROVISION_SERVER", "Provision Server"),
                    ("CONFIGURE_SERVER", "Configure Server"),
                    ("CREATE_INSTANCE", "Create Instance"),
                    ("DELETE_INSTANCE", "Delete Instance"),
                    ("ROLLBACK_INSTANCE", "Rollback Instance"),
                    ("CLONE_INSTANCE_REPO", "Clone Instance Repo"),
                    ("UPDATE_INSTANCE_REPO", "Update Instance Repo"),
                    ("CHECKOUT_INSTANCE_REPO_BRANCH", "Checkout Instance Repo Branch"),
                    ("REMOVE_INSTANCE_REPO", "Remove Instance Repo"),
                    ("REFRESH_INSTANCE_ADDONS", "Refresh Instance Addons"),
                    ("ACTIVATE_ENTERPRISE", "Activate Enterprise"),
                    ("ROLLBACK_INSTANCE_REPO", "Rollback Instance Repo"),
                    ("AUTO_SYNC_INSTANCE_REPOS", "Auto Sync Instance Repos"),
                    ("UPDATE_MODULES_ALL", "Update All Modules"),
                    ("UPDATE_MODULES_SELECTED", "Update Selected Modules"),
                    ("RESTART_INSTANCE", "Restart Instance"),
                    ("CREATE_STAGING_INSTANCE", "Create Staging Instance"),
                    ("DELETE_STAGING_INSTANCE", "Delete Staging Instance"),
                    ("CLEANUP_STAGING_INSTANCE", "Cleanup Staging (TTL)"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="StagingEnvironment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch", models.CharField(max_length=120)),
                ("auto_delete_enabled", models.BooleanField(default=True)),
                ("ttl_days", models.PositiveIntegerField(default=7)),
                ("last_activity_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_staging_environments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staging_environments",
                        to="deployments.odooinstance",
                    ),
                ),
                (
                    "source_repo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staging_environments",
                        to="deployments.odooinstancegitrepo",
                    ),
                ),
                (
                    "staging_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staging_environment",
                        to="deployments.odooinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source_instance", "branch"],
                        name="dep_staging_src_branch_idx",
                    ),
                    models.Index(
                        fields=["auto_delete_enabled", "last_activity_at"],
                        name="dep_staging_ttl_idx",
                    ),
                ],
            },
        ),
    ]
