# Generated by Django 5.2.11 on 2026-04-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0029_odoo_instance_admin_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubwebhookevent",
            name="commits_data",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="odooinstance",
            name="auto_update_core",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="odooinstance",
            name="core_update_channel",
            field=models.CharField(blank=True, default="stable", max_length=20),
        ),
        migrations.AlterField(
            model_name="deploymentjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("PROVISION_SERVER", "Provision Server"),
                    ("CONFIGURE_SERVER", "Configure Server"),
                    ("CREATE_INSTANCE", "Create Instance"),
                    ("DELETE_INSTANCE", "Delete Instance"),
                    ("ROLLBACK_INSTANCE", "Rollback Instance"),
                    ("CLONE_INSTANCE_REPO", "Clone Instance Repo"),
                    ("UPDATE_INSTANCE_REPO", "Update Instance Repo"),
                    ("CHECKOUT_INSTANCE_REPO_BRANCH", "Checkout Instance Repo Branch"),
                    ("REMOVE_INSTANCE_REPO", "Remove Instance Repo"),
                    ("REFRESH_INSTANCE_ADDONS", "Refresh Instance Addons"),
                    ("ACTIVATE_ENTERPRISE", "Activate Enterprise"),
                    ("ROLLBACK_INSTANCE_REPO", "Rollback Instance Repo"),
                    ("AUTO_SYNC_INSTANCE_REPOS", "Auto Sync Instance Repos"),
                    ("UPDATE_MODULES_ALL", "Update All Modules"),
                    ("UPDATE_MODULES_SELECTED", "Update Selected Modules"),
                    ("RESTART_INSTANCE", "Restart Instance"),
                    ("CREATE_STAGING_INSTANCE", "Create Staging Instance"),
                    ("DELETE_STAGING_INSTANCE", "Delete Staging Instance"),
                    ("CLEANUP_STAGING_INSTANCE", "Cleanup Staging (TTL)"),
                    ("BACKUP_INSTANCE", "Backup Instance"),
                    ("RESTORE_INSTANCE", "Restore Instance"),
                    ("DELETE_SERVER", "Delete Server"),
                    ("AUTO_UPDATE_CORE", "Auto-Update Odoo Core"),
                ],
                max_length=30,
            ),
        ),
    ]
