# Generated by Django 5.2.11 on 2026-04-22 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud", "0010_remove_protect_on_delete"),
        ("deployments", "0031_odooserver_platform_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infrastructure",
            name="cloud_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deploy_infrastructure",
                to="cloud.cloudaccount",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructure",
            name="external_server",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deploy_infrastructure",
                to="cloud.externalserver",
            ),
        ),
        migrations.AlterField(
            model_name="odooserver",
            name="cloud_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="odoo_servers",
                to="cloud.cloudaccount",
            ),
        ),
        migrations.AlterField(
            model_name="odooserver",
            name="infrastructure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="servers",
                to="deployments.infrastructure",
            ),
        ),
    ]
