# Generated by Django 5.2.11 on 2026-04-12 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deployments", "0028_initial"),
        ("organizations", "0003_add_first_name_to_invite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OdooInstanceBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full (DB + Filestore)"),
                            ("DB_ONLY", "Database only"),
                        ],
                        default="FULL",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "backup_dir",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "db_backup_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "filestore_backup_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("log", models.TextField(blank=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instance_backups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backups",
                        to="deployments.odooinstance",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instance_backups",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["instance", "-created_at"],
                        name="backups_odo_instanc_737028_idx",
                    ),
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="backups_odo_organiz_c43f21_idx",
                    ),
                ],
            },
        ),
    ]
