# Generated by Django 5.2.11 on 2026-04-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0004_schedule_retention"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="odooinstancebackupschedule",
            new_name="backups_odo_organiz_5621ca_idx",
            old_name="backups_od_organiz_7fe6ff_idx",
        ),
        migrations.AddField(
            model_name="odooinstancebackup",
            name="branch",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="odooinstancebackup",
            name="odoo_version",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="odooinstancebackup",
            name="revision",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Git commit SHA at the time of backup",
                max_length=64,
            ),
        ),
    ]
