# Generated by Django 5.2.11 on 2026-02-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("register", "Register"),
                    ("email_verify", "Email Verified"),
                    ("password_change", "Password Changed"),
                    ("profile_update", "Profile Updated"),
                    ("user_create", "User Created"),
                    ("user_update", "User Updated"),
                    ("user_delete", "User Deleted"),
                    ("role_change", "Role Changed"),
                    ("invite_sent", "Invite Sent"),
                    ("invite_accepted", "Invite Accepted"),
                    ("org_created", "Organization Created"),
                    ("login_failed", "Login Failed"),
                    ("server_add", "Server Added"),
                    ("server_verify", "Server Verified"),
                    ("server_prepare", "Server Prepared"),
                    ("cloud_acct_add", "Cloud Account Added"),
                    ("cloud_acct_verify", "Cloud Account Verified"),
                    ("droplet_provision", "Droplet Provisioned"),
                    ("droplet_destroy", "Droplet Destroyed"),
                    ("social_login", "Social Login"),
                    ("vcs_connect", "VCS Account Connected"),
                    ("vcs_disconnect", "VCS Account Disconnected"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
