# Generated by Django 5.2.11 on 2026-02-22 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0003_add_first_name_to_invite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("STARTER", "Starter"),
                            ("GROWTH", "Growth"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price_monthly", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "max_instances",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum concurrent non-deleted instances. Null = unlimited.",
                        null=True,
                    ),
                ),
                (
                    "max_backups_per_month",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum backup runs per calendar month. Null = unlimited.",
                        null=True,
                    ),
                ),
                ("staging_enabled", models.BooleanField(default=False)),
                ("version_upgrade_enabled", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAST_DUE", "Past Due"),
                            ("CANCELLED", "Cancelled"),
                            ("TRIAL", "Trial"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="TRIAL",
                        max_length=20,
                    ),
                ),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField()),
                ("auto_renew", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("BACKUP", "Backup"),
                            ("STAGING", "Staging"),
                            ("UPGRADE", "Upgrade"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["organization", "usage_type", "timestamp"],
                        name="subscriptio_organiz_18f543_idx",
                    )
                ],
            },
        ),
    ]
