# Generated by Django 5.2.11 on 2026-05-15 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_add_first_name_to_invite"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="paystack_plan_code",
            field=models.CharField(
                blank=True,
                help_text="Paystack plan code (e.g. PLN_xxxx). When set, subscribing initializes a recurring Paystack subscription.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="paystack_customer_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="subscription",
            name="paystack_email_token",
            field=models.CharField(
                blank=True,
                help_text="Token used to generate the Paystack subscription management link.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="paystack_subscription_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="PaystackPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                (
                    "paystack_id",
                    models.CharField(
                        blank=True, help_text="Paystack transaction ID", max_length=100
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="NGN", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Initial subscription"),
                            ("RENEWAL", "Auto-renewal"),
                            ("UPGRADE", "Plan upgrade"),
                        ],
                        default="INITIAL",
                        max_length=20,
                    ),
                ),
                ("gateway_response", models.CharField(blank=True, max_length=255)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paystack_payments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "created_at"],
                        name="subscriptio_organiz_afc69e_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="subscriptio_referen_3a6542_idx"
                    ),
                ],
            },
        ),
    ]
