# Generated by Django 5.2.11 on 2026-02-22 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0003_add_first_name_to_invite"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("DIGITALOCEAN", "DigitalOcean")],
                        default="DIGITALOCEAN",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("encrypted_api_token", models.TextField()),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_error", models.CharField(blank=True, max_length=500)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloud_accounts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CloudServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("provider_server_id", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROVISIONING", "Provisioning"),
                            ("RUNNING", "Running"),
                            ("STOPPED", "Stopped"),
                            ("FAILED", "Failed"),
                            ("DELETED", "Deleted"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cloud_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="servers",
                        to="cloud.cloudaccount",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloud_servers",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("host", models.GenericIPAddressField()),
                ("port", models.PositiveIntegerField(default=22)),
                ("username", models.CharField(default="root", max_length=100)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("SSH_KEY", "SSH Private Key"),
                            ("PASSWORD", "Password"),
                        ],
                        default="SSH_KEY",
                        max_length=10,
                    ),
                ),
                ("encrypted_private_key", models.TextField(blank=True)),
                ("encrypted_password", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_prepared", models.BooleanField(default=False)),
                ("verification_error", models.CharField(blank=True, max_length=500)),
                (
                    "preparation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("preparation_log", models.TextField(blank=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_servers",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Infrastructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "infra_type",
                    models.CharField(
                        choices=[
                            ("PYOS", "PYOS (Own VPS)"),
                            ("MANAGED", "Managed (DigitalOcean)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_ready", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cloud_server",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="infrastructure",
                        to="cloud.cloudserver",
                    ),
                ),
                (
                    "external_server",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="infrastructure",
                        to="cloud.externalserver",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infrastructure",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
