# Generated by Django 5.2.11 on 2026-02-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudaccount",
            name="aws_default_region",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="cloudaccount",
            name="encrypted_aws_access_key_id",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cloudaccount",
            name="encrypted_aws_secret_access_key",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="cloudaccount",
            name="encrypted_api_token",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="cloudaccount",
            name="provider",
            field=models.CharField(
                choices=[
                    ("DIGITALOCEAN", "DigitalOcean"),
                    ("AWS", "Amazon Web Services"),
                ],
                default="DIGITALOCEAN",
                max_length=20,
            ),
        ),
    ]
