# Generated by Django 5.2.11 on 2026-03-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud", "0002_cloudaccount_aws_default_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalserver",
            name="is_reachable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="externalserver",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
