# Generated by Django 5.2.11 on 2026-03-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud", "0003_connectivity_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalserver",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("SSH_KEY", "SSH Private Key"),
                    ("PASSWORD", "Password"),
                    ("DAFEAPP_KEY", "DafeApp SSH Key (public key auth)"),
                ],
                default="SSH_KEY",
                max_length=15,
            ),
        ),
    ]
