# Generated by Django 5.2.11 on 2026-03-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud", "0004_dafeapp_key_auth"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSSHKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_key",
                    models.TextField(
                        help_text="Add this to ~/.ssh/authorized_keys on your server."
                    ),
                ),
                ("encrypted_private_key", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "System SSH Key",
                "verbose_name_plural": "System SSH Keys",
            },
        ),
    ]
