# Generated by Django 5.2.11 on 2026-04-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_pyossshsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudaccount',
            name='do_auth_method',
            field=models.CharField(choices=[('TOKEN', 'Personal Access Token'), ('OAUTH', 'OAuth')], default='TOKEN', max_length=10),
        ),
        migrations.AddField(
            model_name='cloudaccount',
            name='do_oauth_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloudaccount',
            name='encrypted_do_oauth_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cloudaccount',
            name='encrypted_do_oauth_token',
            field=models.TextField(blank=True),
        ),
    ]
