# Generated by Django 5.2.11 on 2026-04-22 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud", "0009_cloudaccount_do_auth_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudserver",
            name="cloud_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servers",
                to="cloud.cloudaccount",
            ),
        ),
    ]
