# Generated by Django 5.2.11 on 2026-04-26 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud", "0010_remove_protect_on_delete"),
        ("organizations", "0003_add_first_name_to_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudaccount",
            name="is_platform",
            field=models.BooleanField(
                default=False,
                help_text="Shared platform account available to all organizations.",
            ),
        ),
        migrations.AlterField(
            model_name="cloudaccount",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cloud_accounts",
                to="organizations.organization",
            ),
        ),
    ]
